### ISSUE TITLE
TypeError: invalid Array.prototype.sort argument

### ISSUE THREAD

**Issue by Hurtak** [storybookjs/react-inspector#31]
In firefox I am getting

```
TypeError: invalid Array.prototype.sort argument[Learn More]  bundle.js:40289:16
```

It happens when
- in FF (Chrome is fine)
- `sortObjectKeys` prop is set (seems to be also broken when it is set to false)
- data is object, eg.: `{}`

**Comment by CodyReichert** [comment]
Yeah, I can reproduce this, thanks for the report. [Here's a webpack bin](https://www.webpackbin.com/bins/-KkMl1vn8ac0df2pDy44) that, if loaded in Firefox, will show the error mentioned above. This does work fine in Chrome.

The issue is [on this line](https://github.com/xyc/react-inspector/blob/d64e9057b51d406704e90145c37b83300d342f13/src/object-inspector/ObjectInspector.js#L36)

The `sort` function expects it's argument to be `undefined` or a function. We're directly passing in the boolean `true` (or false). This should be updated to only pass `sortObjectKeys` if it's a function -- otherwise we should leave the argument as undefined.

Do you want to open up a PR for that? If not, one of us can get something in there soon.
